account/urls.py
from django.urls import path, include, re_path
from .views import signup_view



urlpatterns = [
    path('signup/', signup_view, name='signup')
]

accounts/urls.py
from accounts.views import wishlist_view, current_user_account, edit_user_information, change_user_password
from django.urls import path


app_name = 'account'

urlpatterns = [
    path('wishlist/', wishlist_view, name='wishlist_view'),
    path('my_account/', current_user_account, name="my_account"),
    path('my_account/edit_profile', edit_user_information, name='edit_profile'),
    path('my_account/change_password', change_user_password, name='change_password'),
]

blog/urls.py
from django.urls import path
from blog.views import blog_grid, post_detail, tag_detail_view, category_detail_view


app_name = 'blog'

urlpatterns = [
    path('', blog_grid, name='blog_gird'),
    path('<slug:slug>', post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>/', tag_detail_view, name='tag_detail_view'),
    path('category/<slug:category_slug>', category_detail_view, name='category_detail_view'),
    
]

cart/urls.py
from django.urls import path, include, re_path
from cart.views import cart_detail_view, add_product_to_the_cart, remove_product_from_the_cart, clear_the_cart, apply_discount_for_cart_items


app_name = 'cart'

urlpatterns = [
    path('' , cart_detail_view, name='cart_detail_view'),
    path('add/product/<int:product_id>', add_product_to_the_cart, name='add_to_cart'),
    path('remove/product/<int:product_id>', remove_product_from_the_cart, name='remove_from_the_cart'),
    path('clear', clear_the_cart, name="clear_the_cart"),
    path('apply_discount', apply_discount_for_cart_items, name='apply_discount')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView

urlpatterns = [

    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('blog/', include('blog.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('payment/', include('paymant.urls')),
    path('products/', include('products.urls')),


    # for user configuration we use both allauth and accounts
    # third party urls
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('rosetta', include('rosetta.urls'))


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, include, re_path
from products.views import *

# The first element is the type and the second is the parameter name to use when calling the view, <slug:category_slug>

app_name = 'products'

urlpatterns = [
    path('', shop_categories, name='product_categories'),
    path('<slug:product_slug>', product_detail_view, name='product_detail'), 
    path('<slug:product_slug>/add_to_wishlist', add_to_wishlist, name='add_to_wishlist'),
    path('<slug:product_slug>/remove_from_wishlist', remove_from_wishlist, name='remove_from_wishlist'),
    path('shop_categories/<slug:category_slug>', products_or_category_detail, name='category_detail'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver



class CustomUserModel(AbstractUser):
    # applying Custom change to the AbstractUser field.
    profile_avatar = models.ImageField(upload_to='profile_avatar/', blank=True, default='media/default_avatar/author.webp')
    email = models.EmailField(unique=True)
    
    def profile_avatar_check(self):
        try:
            return self.profile_avatar.url
        except ValueError:
            return '/media/default_avatar/img_avatar.png'
        
    # With the @receiver decorator, we can link a signal with a function
    @receiver(post_save, sender=User)
    def update_profile_signal(sender, instance, created, **kwargs):
        if created:
            CustomUserModel.objects.create(user=instance)
        instance.customusermodel.save()

accounts/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from accounts.models import CustomUserModel
from allauth.account.forms import SignupForm, LoginForm
from config import settings

from allauth.account.forms import LoginForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUserModel
        fields = ['username', 'email', 'profile_avatar', 'first_name', 'last_name']


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUserModel
        fields = ['username', 'email', 'profile_avatar', 'first_name', 'last_name']


# using allauth sign up form
class CustomSignupForm(SignupForm, forms.Form):

    first_name = forms.CharField(
        max_length=settings.FIRST_NAME_MIN_LENGHT,
        widget=forms.TextInput(
            attrs= {
                'placeholder': 'First Name',
                }
        ),
    )
    last_name = forms.CharField(
        max_length=settings.LAST_NAME_MIN_LENGHT,
        widget=forms.TextInput(
            attrs= {
                'placeholder': 'Last Name',
                }
        ),
    )
    profile_avatar = forms.ImageField.hidden_widget
    # forms.ImageField(widget=forms.HiddenInput())

    # overriding the init method
    def __init__(self, *args, **kwargs):
        # call the init of the parent class which here is Sign up Form
        super().__init__(*args, **kwargs)
        # self.fields['username'].widget = forms.HiddenInput()

    def custom_signup(self, request, user):
        user.profile_avatar = 'default_avatar/img_avatar.png'
        user.save()


class CustomLoginForm(LoginForm, forms.Form):
    login = forms.EmailField(
        label="Email",
        widget=forms.EmailInput(attrs={'autofocus': True}),
    )

    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput,
    )

    remember = forms.BooleanField(
        required=True,
        initial=False,
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}),
    )



# this form process when the users want to change their passwords in their account not during reset password process, that process related to allauth django package
class CustomChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(
            attrs={'autocomplete': 'current-password', 'autofocus': True, 'class': 'form-control',
                   'placeholder': 'Old Password'}),
    )

    new_password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'autocomplete': 'new-password', 'class': 'form-control', 'placeholder': 'New Password'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )

    new_password2 = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(
            attrs={'autocomplete': 'new-password', 'class': 'form-control', 'placeholder': 'Confirm password'}),
    )

        

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import SignupForm


def signup_view(request):
    signup_form = SignupForm(request.POST)
    if signup_form.is_valid():
        user = signup_form.save()
        # refresh_from_db() method  handle synchronism issue, basically reloading the database after the signal
        user.refresh_from_db()
        # choose basic avatar photo for every user
        user.profile_avatar = 'default/img_avatar.png'
        user.save()
        # cleaned_data is holding the validated form data
        username = signup_form.cleaned_data.get('username')
        password = signup_form.cleaned_data.get('password1')
        email = signup_form.cleaned_data.get('email')
        # authenticate() method takes credentials as keyword arguments
        user = authenticate(username=username, password=password, email=email)
        # login() method takes an HttpRequest object and a User object and saves the user’s ID in the session
        login(request, user)
        print(request.session.session_key)
        return redirect('homepage')
    else:
        signup_form = SignupForm()
    return render(request, 'registration/signup.html', {'signup_form': signup_form})

accounts/views.py
import logging
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest
from django.shortcuts import render, redirect
from django.utils import timezone
from django.utils.translation import gettext as _
from django.views.decorators.http import require_POST
from accounts.forms import CustomUserChangeForm, CustomChangePasswordForm
from accounts.models import CustomUserModel
from accounts.utils import persian_to_western_digits
from orders.forms import CustomerWithAddressForm
from orders.models import Order

# const values for breadcrumb data
breadcrumb_my_account = _('my_account')


@login_required
def wishlist_view(request):

    login_user = CustomUserModel.objects.prefetch_related('wished_product').get(username=request.user.username)


    breadcrumb_data = [{'lable': _('wishlist'), 'title': _('wishlist')}]
    return render(request, 'accounts/wishlist.html', context={'breadcrumb_data': breadcrumb_data, 'login_user': login_user,})


@login_required
def current_user_account(request):
    # accsesing users order
    user_orders = Order.objects.prefetch_related('items').filter(customer__user=request.user, status='Paid')

    breadcrumb_data = [{'lable': breadcrumb_my_account,'title': breadcrumb_my_account}]

    context = {
        'order_form': CustomerWithAddressForm(),
        'user_change_form': CustomUserChangeForm(),
        'password_change_form': CustomChangePasswordForm(user=request.user),
        'user_orders': user_orders,
        'current_time': persian_to_western_digits(timezone.now().strftime('%Y-%m-%d')),
        'breadcrumb_data': breadcrumb_data,
    }

    return render(request, 'accounts/my_account.html', context)


@login_required
@require_POST
def edit_user_information(request):
    user = request.user
    if request.method == 'POST':
        user_change_information_form = CustomUserChangeForm(request.POST, instance=user)
        if user_change_information_form.is_valid():
            user_change_information_form.save()
            messages.success(request, 'your information updated successfully')
            return redirect('account:my_account')
        else:
            # Log form errors
            logger = logging.getLogger(__name__)
            logger.error("Form validation failed: %s", user_change_information_form.errors)
            # creating an error response
            error_message = f"Form validation failed: {user_change_information_form.errors}"
            response = HttpResponseBadRequest(error_message)
            return response
    else:
        user_change_information_form = CustomUserChangeForm()


@login_required
def change_user_password(request):
    user = request.user
    if request.method == 'POST':
        change_password_form = CustomChangePasswordForm(user, request.POST)
        if change_password_form.is_valid():
            change_password_form.save()
            messages.success(request, 'your password has been changed successfully')
            return redirect('account:my_account')
        else:
            # Log form errors
            logger = logging.getLogger(__name__)
            logger.error("Form validation failed: %s", change_password_form.errors)
            # creating an error response
            error_message = f"Form validation failed: {change_password_form.errors}"
            response = HttpResponseBadRequest(error_message)
            return response
    else:
        change_password_form = CustomChangePasswordForm()

accounts/templates/accounts/wishlist.html
{% extends '_base.html' %}
{% load  static %}
{% load humanize %}


{% block page_title %}Wishlist{% endblock page_title %}

{% block content %}
    <!-- breadcrumb-area start -->
    {% include "breadcrumb.html" %}
    <!-- breadcrumb-area end -->
    <div class="site-wrapper-reveal border-bottom"> 
        <!-- wishlist start -->             
        <div class="wishlist-main-area  section-space--ptb_90"> 
            <div class="container"> 
                <div class="row"> 
                    <div class="col-lg-12"> 
                        {% if login_user.wished_product.all %}
                            <div class="table-content table-responsive cart-table-content"> 
                                <table> 
                                    <thead> 
                                        <tr> 
                                            <th></th> 
                                            <th></th> 
                                            <th class="product-name">محصول</th> 
                                            <th class="product-price">قیمت</th> 
                                            <th>وضعیت</th> 
                                            <th></th> 
                                        </tr>                                             
                                    </thead>                                         
                                    <tbody>
                                            {% for product in login_user.wished_product.all %}
                                                <form action={% url 'cart:add_to_cart' product.id %} method='post' >
                                                    {% csrf_token %}
                                                    <tr> 
                                                        <td class="product-remove">  <a href="{% url 'products:remove_from_wishlist' product.slug %}"><i class="icon-cross2"></i></a>  </td> 
                                                        <td class="product-img">  <a href="#"><img src="{% static 'images/product/small/cart-01.webp' %}" alt=""/></a>  </td> 
                                                        <td class="product-name"><a href="{% url 'products:product_detail' product.slug %}">{{ product.name }}</a></td> 
                                                        <td class="product-price"><span class="amount">{{ product.clean_price }} تومان</span></td>
                                                        {% if product.activation %} 
                                                            <td class="product-stock-status"><p>موجود در انبار</p></td> 
                                                        {% elif not product.activation %}
                                                            <td class="product-stock-status"><p style="color: red;">ناموجود در انبار</p></td>
                                                        {% endif %}
                                                        <div class="quickview-quality">
                                                            <input class="cart-plus-minus-box" name='quantity' type='hidden' value=1 widget>
                                                            <input class="cart-plus-minus-box" name='size' value='LARGE' type='hidden'>  
                                                            <input class="cart-plus-minus-box" name='color' value='BLACK' type='hidden'>    
                                                        </div>
                                                        <td class="product-wishlist-cart">
                                                            {% if product.activation %}
                                                                {% if product.id|stringformat:"s" not in request.session.cart.keys %}
                                                                    <button type='submit' class="btn--lg btn--black font-weight--reguler text-white">افزودن به سبد خرید</button>
                                                                {% else %}
                                                                    <button type='button'class="btn--lg btn--black font-weight--reguler text-white" >  مشاهده <a href={% url 'cart:cart_detail_view' %}>سبد خرید</a></button>
                                                                {% endif %}
                                                            {% endif %}
                                                        </td> 
                                                    </tr>
                                                </form>
                                            {% endfor %}
                                    </tbody>                                         
                                </table>                                     
                            </div>                                 
                        {% elif not login_user.wished_product.all %}
                        <tr>
                            <td>
                            </td>
                        </tr> 
                        {% endif %}
                    </div>                         
                </div>                     
            </div>                 
        </div>             
        <!-- wishlist end -->             
    </div>
{% endblock content %}