blog/urls.py
from django.urls import path
from blog.views import blog_grid, post_detail, tag_detail_view, category_detail_view


app_name = 'blog'

urlpatterns = [
    path('', blog_grid, name='blog_gird'),
    path('<slug:slug>', post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>/', tag_detail_view, name='tag_detail_view'),
    path('category/<slug:category_slug>', category_detail_view, name='category_detail_view'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView

urlpatterns = [

    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('blog/', include('blog.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('payment/', include('paymant.urls')),
    path('products/', include('products.urls')),


    # for user configuration we use both allauth and accounts
    # third party urls
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('rosetta', include('rosetta.urls'))


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.html import strip_tags
from accounts.models import CustomUserModel
from ckeditor.fields import RichTextField


# managers
class IsPublishedManager(models.Manager):
    
    def get_queryset(self):
        return super(IsPublishedManager, self).get_queryset().filter(is_published=True)        


class IsNotSpamManager(models.Manager):
    
    def get_queryset(self):
        return super(IsNotSpamManager, self).get_queryset().filter(is_spam=False)


class Post(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    content = RichTextField()
    # In this model only superusers have the permission to published posts
    author = models.ForeignKey(CustomUserModel, on_delete=models.CASCADE, limit_choices_to={'is_superuser': True})
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    is_published = models.BooleanField(default=False)
    datetime_created = models.DateTimeField(auto_now=True)
    datetime_modified = models.DateTimeField(auto_now_add=True)
    list_view_image = models.ImageField(upload_to='blog_images/', blank=True, null=True, default='media\blog_images\1-570x370.webp')
    detail_view_image = models.ImageField(upload_to='blog_images/', blank=True, null=True, default='media\blog_images\1-870x500.webp')
    small_detail_view_image = models.ImageField(upload_to='blog_images/', blank=True, null=True, default='media\blog_images\1-420x241.webp') 
    small_detail_view_image_2 = models.ImageField(upload_to='blog_images/', blank=True, null=True, default='media\blog_images\1-420x241.webp')           
    tags = models.ManyToManyField('Tag', related_name='posts', blank=True)
    category = models.ForeignKey('Category', related_name='posts', blank=True, null=True, on_delete=models.CASCADE)

    # Custom Managers
    objects = models.Manager()
    is_published_manager = IsPublishedManager()


    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[str(self.slug)])

    def __str__(self):
        return f'{self.author}: {self.title}'
    

    def get_content_summary(self):
        content = strip_tags(self.content)
        return content[:70] 


class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    content = RichTextField()
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='post_comments')
    timestamp = models.DateTimeField(auto_now_add=True)
    is_spam = models.BooleanField(default=False)

    # Custom Managers
    objects = models.Manager()
    is_not_spam_manager = IsNotSpamManager()


    def __str__(self):
        return f"{self.author}'s comment, id:{self.id}"
    

    def get_absolute_url(self):
        return reverse('blog:comment_detail', args=[str(self.slug)])
    
    
    def get_content_summary(self):
        content = strip_tags(self.content)
        return content[:30] 

blog/forms.py
from django import forms
from blog.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        # we fill author and post manually in the product_detail_views
        fields = ['content']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['website'] = forms.CharField(
        required=False,
        help_text="Please leave this field blank",
    ) 

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.utils.translation import gettext as _
from blog.forms import CommentForm
from blog.models import Post, Tag,  Category, Comment

# const values for breadcrumb data
breadcrumb_blog = _('blog')


def blog_grid(request):
    posts = Post.is_published_manager.all()

    # Create a Paginator object
    page_number = request.GET.get('page')
    paginator = Paginator(posts, 9)

    # Get the current page
    page_obj = paginator.get_page(page_number)

    breadcrumb_data = [{'lable': breadcrumb_blog, 'title': breadcrumb_blog}]

    context = {
        'page_obj': page_obj,
        'breadcrumb_data': breadcrumb_data,
    }
    return render(request, 'blog/blog_grid.html', context)


def post_detail(request, slug):
    posts = Post.is_published_manager.all()
    post = get_object_or_404(posts, slug=slug)
    # comment section
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            # Check the Honeypot Field
            if comment_form.cleaned_data.get('website') != "Leave this field blank" :
                new_comment.is_spam = True
            new_comment.post = post
            new_comment.author = request.user
            new_comment.save()
            return redirect(post.get_absolute_url())
    else:
        comment_form = CommentForm()

    breadcrumb_data = [{'lable': f'{post.title}', 'title':f'{post.title}', 'middle_lable': breadcrumb_blog , 'middle_url':'blog:blog_gird'}]

    context = {
        'post_detail': post,
        'tags': Tag.objects.all(),
        'categories': Category.objects.all(),
        'third_latest_post': Post.is_published_manager.order_by('-published_date')[:3],
        'comment_form': CommentForm(),
        'comments': Comment.is_not_spam_manager.filter(post=post).order_by('-timestamp'),
        'breadcrumb_data': breadcrumb_data,
    }
    return render(request, 'blog/post_detail.html', context)

def tag_detail_view(request, tag_slug):
    # get posts related to a tag
    tags = Tag.objects.all()
    tag = get_object_or_404(tags, slug=tag_slug)
    # defining 'posts' as a related name for tag field in Blog model
    tag_posts = tag.posts.all()

    # Create a Paginator object
    page_number = request.GET.get('page')
    paginator = Paginator(tag_posts, 9)

    # Get the current page
    page_obj = paginator.get_page(page_number)

    breadcrumb_data = [{'lable': (tag.name + _('tag')), 'title': (tag.name + _('tag')), 'middle_lable': breadcrumb_blog ,'middle_url':'blog:blog_gird'}]
    
    context = {
        'page_obj': page_obj,
        'tag': tag, 
        'breadcrumb_data': breadcrumb_data,
    }
    return render(request, 'blog/tag_detail_view.html', context)



def category_detail_view(request, category_slug):
    # get posts related to a category
    categories = Category.objects.all()
    category = get_object_or_404(categories, slug=category_slug)

    # defining 'posts' as a related name for category field in Blog model
    category_posts = category.posts.all()

     # Create a Paginator object
    page_number = request.GET.get('page')
    paginator = Paginator(category_posts, 9)

    # Get the current page
    page_obj = paginator.get_page(page_number)

    breadcrumb_data = [{'lable': (category.name + _('category')), 'title': (category.name + _('category')), 'middle_lable': breadcrumb_blog ,'middle_url':'blog:blog_gird'}]

    context = {
        'page_obj': page_obj,
        'category': category,
        'breadcrumb_data': breadcrumb_data,
    }
    return render(request, 'blog/category_detail_view.html', context)

blog/templates/blog/blog_grid.html
{% extends '_base.html' %}
{% load humanize %}
 
{% block content %}
    <!-- breadcrumb-area start -->         
    {% include 'breadcrumb.html' %}
    <!-- breadcrumb-area end -->       
    <div id="main-wrapper"> 
        <div class="site-wrapper-reveal border-bottom"> 
            <!-- Blog Page Area Start -->                 
            {% include "blog/blog_page_area.html" %}          
            <!-- Blog Page Area End -->                 
        </div>                      
    </div>    
{% endblock content %}
    
    

      

blog/templates/blog/blog_page_area.html
{% block content %}
    <div class="blog-page-wrapper section-space--pt_90 section-space--pb_120"> 
        <div class="container"> 
            <div class="row">
                {% for post in page_obj %}                 
                    <div class="col-lg-4 col-md-6 col-sm-6 col-12"> 
                        <!-- Single Blog Item Start -->                                 
                        <div class="single-blog-item mt-40"> 
                            <div class="blog-thumbnail-box"> <a href="{{post.get_absolute_url}}" class="thumbnail"> <img src="{{post.list_view_image.url}}" class="img-fluid" alt="Blog Images"/> </a> <a href="{{post.get_absolute_url}}" class="btn-blog"> مطالعه بیشتر </a> 
                            </div>                                     
                            <div class="blog-contents"> 
                                <h6 class="blog-title"><a href="{{post.get_absolute_url}}">{{post.title}}</a></h6> 
                                <div class="meta-tag-box"> 
                                    <div class="meta date"><span>{{post.published_date}}</span>
                                    </div>                                             
                                    {% comment %} <div class="meta author"><span><a href="#">طراحی</a></span>
                                    </div>                                              {% endcomment %}
                                    <div class="meta cat"><span>دسته <a href={% url 'blog:category_detail_view' post.category.slug %}>{{post.category.name}}</a></span>   
                                    </div>                                             
                                </div>                                         
                            </div>                                     
                        </div>
                        <!-- Single Blog Item End -->                                 
                    </div>
                {% endfor %}                                                                                         
            </div>     
            <div class="row"> 
                <div class="col-12"> 
                    <ul class="page-pagination text-start mt-40"> 
                        {% if page_obj.has_previous %}                                     
                        <li>
                            <a class="page-numbers" href="?page={{page_obj.previous_page_number}}">صفحه قبل<i class="icon-chevron-left"></i></a>
                        </li>
                        {% endif %}
                        <li>
                            <span class="page-numbers current">{{page_obj.number}}</span>
                        </li>
                        {% if page_obj.has_next %}                                     
                            <li>
                                <a class="next page-numbers" href="?page={{page_obj.next_page_number}}">صفحه بعد<i class="icon-chevron-right"></i></a> 
                            </li>
                        {% endif %}
                    </ul>                                 
                </div>                             
            </div>    
        </div>                         
    </div>       
{% endblock content%}

blog/templates/blog/category_detail_view.html
{% extends '_base.html' %}
{% load humanize %}
 
{% block content %}
    <!-- breadcrumb-area start -->         
    {% include 'breadcrumb.html' %}
    <!-- breadcrumb-area end -->       
    <div id="main-wrapper"> 
        <div class="site-wrapper-reveal border-bottom"> 
            <!-- Blog Page Area Start -->                 
            {% include "blog/blog_page_area.html" %}                     
            <!-- Blog Page Area End -->                 
        </div>                      
    </div>    
{% endblock content %}
    
    

      

blog/templates/blog/tag_detail_view.html
{% extends '_base.html' %}
{% load humanize %}
 
{% block content %}
    <!-- breadcrumb-area start -->         
    {% include 'breadcrumb.html' %}     
    <!-- breadcrumb-area end -->       
    <div id="main-wrapper"> 
        <div class="site-wrapper-reveal border-bottom"> 
            <!-- Blog Page Area Start -->                 
            {% include "blog/blog_page_area.html" %}                     
            <!-- Blog Page Area End -->                 
        </div>                      
    </div>    
{% endblock content %}
    
    

      