blog/urls.py
from django.urls import path
from blog.views import blog_grid, post_detail, tag_detail_view, category_detail_view


app_name = 'blog'

urlpatterns = [
    path('', blog_grid, name='blog_gird'),
    path('<slug:slug>', post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>/', tag_detail_view, name='tag_detail_view'),
    path('category/<slug:category_slug>', category_detail_view, name='category_detail_view'),
    
]

cart/urls.py
from django.urls import path, include, re_path
from cart.views import cart_detail_view, add_product_to_the_cart, remove_product_from_the_cart, clear_the_cart, apply_discount_for_cart_items


app_name = 'cart'

urlpatterns = [
    path('' , cart_detail_view, name='cart_detail_view'),
    path('add/product/<int:product_id>', add_product_to_the_cart, name='add_to_cart'),
    path('remove/product/<int:product_id>', remove_product_from_the_cart, name='remove_from_the_cart'),
    path('clear', clear_the_cart, name="clear_the_cart"),
    path('apply_discount', apply_discount_for_cart_items, name='apply_discount')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView

urlpatterns = [

    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('blog/', include('blog.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('payment/', include('paymant.urls')),
    path('products/', include('products.urls')),


    # for user configuration we use both allauth and accounts
    # third party urls
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('rosetta', include('rosetta.urls'))


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path, include, re_path
from orders.views import checkout, create_and_update_customer, order_create


app_name = 'orders'

urlpatterns = [
    path('checkout/', checkout, name='checkout'),
    path('customer_create', create_and_update_customer, name='create_and_update_customer'),
    path('order_create', order_create, name='order_create')
]

products/urls.py
from django.urls import path, include, re_path
from products.views import *

# The first element is the type and the second is the parameter name to use when calling the view, <slug:category_slug>

app_name = 'products'

urlpatterns = [
    path('', shop_categories, name='product_categories'),
    path('<slug:product_slug>', product_detail_view, name='product_detail'), 
    path('<slug:product_slug>/add_to_wishlist', add_to_wishlist, name='add_to_wishlist'),
    path('<slug:product_slug>/remove_from_wishlist', remove_from_wishlist, name='remove_from_wishlist'),
    path('shop_categories/<slug:category_slug>', products_or_category_detail, name='category_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

class AddToCartForm(forms.Form):

    def __init__(self, *args, **kwargs):
        product_stock = kwargs.pop('product_stock')
        super(AddToCartForm, self).__init__(*args, **kwargs)
        QUANTITY_CHOICES = [(i, str(i)) for i in range(1, int(product_stock) + 1)]
        COLOR_CHOICES =  (('BLACK', 'black'),('WHITE', 'white'),('PINK', 'pink'))
        SIZE_CHOICES = (('LARGE', 'large'),('MEDIUM', 'medium'),('SMALL', 'small'))
        self.fields['quantity'] = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int, required=True)
        self.fields['color'] = forms.ChoiceField(choices=COLOR_CHOICES, required=True)
        self.fields['size'] =  forms.ChoiceField(choices=SIZE_CHOICES, required=True)

cart/views.py
import logging
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import gettext as _
from cart.cart import Cart
from cart.decorators import item_in_cart_required
from cart.forms import AddToCartForm
from products.forms import DiscountForm
from products.models import Discount
from products.models import Product

# const values for breadcrumb data
breadcrumb_cart = _('cart')

logger = logging.getLogger(__name__)

@item_in_cart_required
def cart_detail_view(request):
    cart = Cart(request)

    breadcrumb_data = [{'lable': breadcrumb_cart, 'title': breadcrumb_cart}]


    context = {
        'cart': cart,
        'breadcrumb_data': breadcrumb_data,
    }

    return render(request, 'cart_detail_view.html', context)


# we use this view as action of our forms in 'cart_detail_view' and 'product_detail_view'
def add_product_to_the_cart(request, product_id):
    cart = Cart(request)
    products = Product.objects.all()
    product = get_object_or_404(products, id=product_id)
    add_to_cart_form = AddToCartForm(request.POST, product_stock=product.quantity)

    if add_to_cart_form.is_valid():
        # getting product variant from input that fill by the user
        cleaned_data = add_to_cart_form.cleaned_data

        quantity = cleaned_data.get('quantity', 1)
        size = cleaned_data.get('size')
        color = cleaned_data.get('color')

        cart.add_to_cart(product, size=size, color=color, quantity=quantity)
        return redirect('cart:cart_detail_view')
    else:
        # Log form errors
        logger.error("Form validation failed: %s", add_to_cart_form.errors)

        # creating an error response
        error_message = f"Form validation failed: {add_to_cart_form.errors}"
        response = HttpResponseBadRequest(error_message)
        return response


def remove_product_from_the_cart(request, product_id):
    cart = Cart(request)
    products = Product.objects.all()
    product = get_object_or_404(products, id=product_id)

    cart.remove_from_the_cart(product)

    messages.success(request, _('{product_name} product deleted from your cart successfully.').format(product_name=product.name))
 
    return redirect(request.META.get('HTTP_REFERER'))


def clear_the_cart(request):
    cart = Cart(request)

    cart.clear_the_cart()

    messages.success(request, _('your cart deleted successfully'))

    #redirect the user to the previous page.
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def apply_discount_for_cart_items(request):
    cart = Cart(request)

    discount_form = DiscountForm(request.POST)

    if discount_form.is_valid():
        entered_promo_code = discount_form.cleaned_data.get('promo_code')
        discount_obj = get_object_or_404(Discount ,promo_code=entered_promo_code, status='AC')
        target_products = Product.objects.filter(id__in=request.session['cart'].keys(), discounts=discount_obj)
        unapplied_discounted_product = []
        applied_discounted_product = []
        str_discount_obj_id = str(discount_obj.id)

        if target_products.exists() and not discount_obj.usage_by.filter(id=request.user.id).exists():
            # Retrieve user discounts from session or initialize it
            user_discounts = request.session.get('user_discounts', {})
        
            if f'discount_{str_discount_obj_id}' not in user_discounts:
                user_discounts[f'discount_{str_discount_obj_id}'] = {
                    'id': discount_obj.id,
                    'promo_code' : discount_obj.promo_code,
                    'products': {},
                }


            for product in target_products:
                str_product_id = str(product.id)

                # adding discount to a product for the first time
                if str_product_id not in user_discounts[f'discount_{str_discount_obj_id}']['products']:
                    user_discounts[f'discount_{str_discount_obj_id}']['products'][str_product_id] = product.name

                    unapplied_discounted_product.append(product.name)

                    # applied discount
                    cart.applied_discount(discount_obj, product)
                else:
                    applied_discounted_product.append(product.name)

            # Update the session with the modified 'user_discounts'
            request.session['user_discounts'] = user_discounts
            request.session.modified = True

            # Give feedback to user if discount applied to targeted product or not 
            if unapplied_discounted_product:
                messages.success(
                    request, 
                    _("{promo_code} applied for {unapplied_discount_products} successfully.").format(
                        promo_code = discount_obj.promo_code,
                        unapplied_discount_products = (','.join(unapplied_discounted_product))
                    )
                )
                return redirect(request.META.get('HTTP_REFERER'))
        
            elif applied_discounted_product:
                messages.error(
                    request, 
                    _("{promo_code} has been applied for {applied_discount_products} before.").format(
                        promo_code = discount_obj.promo_code,
                        applied_discount_products = (','.join(applied_discounted_product))
                    )
                )
                return redirect(request.Meta.get('HTTP_REFERER'))
            
        else:
            messages.error(
                request, 
                _('{promo_code} discount is not match to any items in the cart.').format(
                    promo_code=discount_obj.promo_code
                )
            )
            return redirect(request.META.get('HTTP_REFERER'))
    else:
        # Log form errors
        logger.error("Form validation failed: %s", discount_form.errors)

        # creating an error response
        error_message = f'{discount_form.errors}'
        response = HttpResponseBadRequest(error_message)
        return response

cart/templates/cart_detail_view.html
{% extends '_base.html' %}
{% load static %}
{% load humanize %}
{% load custom_intcomma %}

{% block content %}
    <!-- breadcrumb-area start -->
    {% include 'breadcrumb.html'%}
    <!-- breadcrumb-area end -->
    
    <!-- cart start -->                 
    <div class="cart-main-area  section-space--ptb_90"> 
        <div class="container"> 
            <div class="row"> 
                <div class="col-lg-12">
                    <div class="table-content table-responsive cart-table-content header-color-gray"> 
                        <table> 
                            <thead> 
                                <tr class="bg-gray"> 
                                    <th></th> 
                                    <th></th> 
                                    <th class="product-name">محصول</th> 
                                    <th class="product-price">قیمت</th> 
                                    <th>تعداد</th> 
                                    <th>جمع</th> 
                                    <th></th> 
                                </tr>                                                 
                            </thead>                                             
                            <tbody>
                                {% for item in cart %} 
                                    <tr> 
                                        <td></td> 
                                        <td class="product-img"> <a href="#"><img src={% static "images/product/small/cart-01.webp" %} alt=""/></a> </td> 
                                        <td class="product-name"><a href={% url 'products:product_detail' item.product_obj.slug %}>{{item.product_obj.name}}</a></td> 
                                        {% if item.discounted_price %}
                                            <td class="product-price"><span class="amount">{{item.discounted_price|custom_intcomma}} تومان</span></td> 
                                        {% else %}
                                            <td class="product-price"><span class="amount">{{item.product_obj.price|custom_intcomma}} تومان</span></td> 
                                        {% endif %}
                                        <td class="cart-quality">
                                            <form action={% url 'cart:add_to_cart' item.product_obj.id %} method='post'>
                                                {% csrf_token %} 
                                                <div class="quickview-quality quality-height-dec2"> 
                                                    <div class="cart-plus-minus"> 
                                                        <input class="cart-plus-minus-box" type="number" name="quantity" value={{item.quantity}}>    
                                                    </div>
                                                    <input type='hidden' name='size' value={{item.size}}>
                                                    <input type='hidden' name='color' value={{item.color}}>
                                                    {{item.update_quantity_of_the_current_form.inplace}}
                                                    <button type='submit'  class="btn btn--sm btn--border_1">به روز رسانی سبد خرید</button>   
                                                </div>

                                            </form>                                                         
                                        </td>
                                        {% if item.total_discounted_price %}                                                     
                                            <td class="price-total"> <span class="amount">{{item.total_discounted_price|custom_intcomma}} تومان</span> </td>
                                        {% elif item.total_price%}
                                            <td class="price-total"> <span class="amount">{{item.total_price|custom_intcomma}} تومان</span> </td> 
                                        {% endif %}
                                        <td class="product-remove"> <a href={% url 'cart:remove_from_the_cart' item.product_obj.id %}><i class="icon-cross2"></i></a> </td> 
                                    </tr>
                                {% endfor %}                                                                                                                          
                            </tbody>                                             
                        </table>                                         
                    </div> 
                    <div class="shoping-update-area row"> 
                        <div class="continue-shopping-butotn col-6 mt-30"> 
                            <a href={% url 'cart:clear_the_cart' %}  class="btn btn--lg btn--border_1"><i class="icon-cross2"></i>&nbsp; حذف سبد خرید</a>
                        </div>                                     
                        <div class="update-cart-button col-6 text-end mt-30"> 
                            <a href={% url 'products:product_categories' %}  class="btn btn--lg btn--black">ادامه خرید <i class="icon-arrow-right"></i>&nbsp;</a>           
                        </div>                               
                    </div>                                 
                    <div class="cart-buttom-area"> 
                        <div class="row">
                            <div class="col-lg-6"> 
                                    <form action={% url 'cart:apply_discount'%} method='post'>
                                        {% csrf_token %} 
                                        <div class="discount-code section-space--mt_60"> 
                                            <h6 class="mb-30">کد تخفیف</h6> 
                                            <p>اگر کد تخفیف دارید، وارد نمایید.</p> 
                                            <input type="text" name="promo_code" placeholder="کد تخفیف"/> 
                                            <button class="coupon-btn btn btn--lg btn--border_1" type="submit">ثبت کد تخفیف</button>                                                 
                                        </div>                                             
                                    </form>
                                </div>
                            <div class="col-lg-6"> 
                                <div class="cart_totals section-space--mt_60 ms-md-auto"> 
                                    <div class="grand-total-wrap"> 
                                        <div class="grand-total-content"> 
                                            <ul> 
                                                <li>مجموع قیمت<span> {{cart.get_total_price|custom_intcomma}} تومان</span>
                                                </li>                                                  
                                                <li>مجموع قیمت (با احتساب تخفیف)<span>{{cart.get_total_discounted_price|custom_intcomma}} تومان</span>
                                                </li>                                                       
                                            </ul>                                                         
                                        </div>                                                     
                                    </div>                                                 
                                    <div class="grand-btn mt-30"> <a href={% url 'orders:checkout' %} class="btn--black btn--full text-center btn--lg">تسویه حساب</a> 
                                    </div>                                                 
                                </div>                                             
                            </div>                                         
                        </div>                                     
                    </div>                                 
                </div>                             
            </div>                         
        </div>                     
    </div>                 
    <!-- cart end -->                     
{% endblock content %}