blog/urls.py
from django.urls import path
from blog.views import blog_grid, post_detail, tag_detail_view, category_detail_view


app_name = 'blog'

urlpatterns = [
    path('', blog_grid, name='blog_gird'),
    path('<slug:slug>', post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>/', tag_detail_view, name='tag_detail_view'),
    path('category/<slug:category_slug>', category_detail_view, name='category_detail_view'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView

urlpatterns = [

    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('blog/', include('blog.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('payment/', include('paymant.urls')),
    path('products/', include('products.urls')),


    # for user configuration we use both allauth and accounts
    # third party urls
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('rosetta', include('rosetta.urls'))


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path, include, re_path
from .views import homepage

# The first element is the type and the second is the parameter name to use when calling the view, <slug:category_slug>

app_name = 'pages'

urlpatterns = [
    path('', homepage, name='homepage')
]

products/urls.py
from django.urls import path, include, re_path
from products.views import *

# The first element is the type and the second is the parameter name to use when calling the view, <slug:category_slug>

app_name = 'products'

urlpatterns = [
    path('', shop_categories, name='product_categories'),
    path('<slug:product_slug>', product_detail_view, name='product_detail'), 
    path('<slug:product_slug>/add_to_wishlist', add_to_wishlist, name='add_to_wishlist'),
    path('<slug:product_slug>/remove_from_wishlist', remove_from_wishlist, name='remove_from_wishlist'),
    path('shop_categories/<slug:category_slug>', products_or_category_detail, name='category_detail'),
]

templates/breadcrumb.html
{% load i18n %}


{% block content %}
    <div class="breadcrumb-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="row breadcrumb_box  align-items-center">
                        {% for item in breadcrumb_data %}
                            <div class="col-lg-6 col-md-6 col-sm-6 text-center text-sm-start">
                                <h2 class='breadcrumb'>{{item.title}}</h2>
                            </div>
                            <div class="col-lg-6  col-md-6 col-sm-6">
                                <!-- breadcrumb-list start -->
                                    <ul class="breadcrumb-list text-center text-sm-end">
                                        <li class="breadcrumb-item"><a href="{% url 'pages:homepage' %}">
                                            {% trans 'Homepage'%}
                                        </a></li>
                                        {% if item.middle_lable %}
                                            <li class="breadcrumb-item">
                                                {% if item.middle_url %}
                                                    {% if item.middle_url and item.middle_url_args %}
                                                        <a href="{% url item.middle_url item.middle_url_args %}">
                                                    {% else %}
                                                        <a href="{% url item.middle_url %}">
                                                    {% endif %}
                                                {% endif %}
                                                {{item.middle_lable}}
                                            </a></li>
                                        {% endif %}
                                        <li class="breadcrumb-item active">
                                            {% if item.url %}
                                                <a href="{% url item.url %}">
                                            {% endif %}
                                            {{item.lable}}
                                        </a></li>
                                    </ul>
                                <!-- breadcrumb-list end -->
                            </div>
                            {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content%}

templates/home.html
{# later you should add a navbar in your _base.html that includes categories and sub categories #}
{% extends '_base.html' %}
{% load static %}

{% block page_title %}Homepage{% endblock%}

{% block content %}
    <div class="hero-box-area mt-md-0 mt-lg-3">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 ps-0 ps-lg-3 pe-0 pe-lg-3">
                    <!-- Hero Slider Area Start -->
                    <div class="hero-area hero-slider-one">
                        <div class="single-hero-slider-one bg-img"
                             data-bg="{% static "images/hero/home-default-1.jpg" %}">
                            <div class="container">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="hero-text-one">
                                            <h6 class="text-color-primary mb-10">
                                            کالکشن <br/> مبلمان <br/> 2022 </h6>
                                            <h1 class="hero-title">
                                            به فروشگاه هلندو <br/>  خوش آمدید </h1>
                                            <p class="mt-30"> لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ <br/>
                                            و با استفاده از طراحان گرافیک است. </p>
                                            <div class="button-box mt-30"> <a href="#" class="hero-btn-one btn">الآن خرید کنید <i class="icon-arrow-right"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="single-hero-slider-one bg-img"
                             data-bg="{% static "images/hero/home-default-2.jpg" %}">
                            <div class="container">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="hero-text-one">
                                            <h6 class="text-color-primary mb-10">
                                            کالکشن <br/> مبلمان <br/> 2022 </h6>
                                            <h1 class="hero-title">
                                            به فروشگاه هلندو <br/>  خوش آمدید </h1>
                                            <p class="mt-30"> لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ <br/>
                                            و با استفاده از طراحان گرافیک است. </p>
                                            <div class="button-box mt-30"> <a href="shop-3-column.html" class="hero-btn-one btn">الآن خرید کنید <i class="icon-arrow-right"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="single-hero-slider-one bg-img"
                             data-bg="{% static "images/hero/home-default-3.jpg" %}">
                            <div class="container">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="hero-text-one">
                                            <h6 class="text-color-primary mb-10">
                                            کالکشن <br/> مبلمان <br/> 2022 </h6>
                                            <h1 class="hero-title">
                                            به فروشگاه هلندو <br/>  خوش آمدید </h1>
                                            <p class="mt-30"> لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ <br/>
                                            و با استفاده از طراحان گرافیک است. </p>
                                            <div class="button-box mt-30"> <a href="shop-3-column.html" class="hero-btn-one btn">الآن خرید کنید <i class="icon-arrow-right"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Hero Slider Area End -->
                </div>
            </div>
        </div>
    </div>
    {% for product in products %}
        <div class="featuted-product-wrap section-space--pt_120">
            <div class="container">
                <div class="row align-items-center featuted-product-one">
                    <div class="col-lg-6 col-md-6 order-md-1 order-1">
                        <div class="product-thumbnail"> <a href={% url 'product_detail' product.slug %}>
                            <img src="{{ product.image.url }}" class="img-flu %}id"
                                 alt="Featured Image" height="451" width="397"/></a>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 order-md-2 order-2">
                        <div class="featured-product-contect">
                            <h6 class="sub-heading mb-2">محصول ویژه</h6>
                            <h2 class="section-title--one"><a href={% url 'product_detail' product.slug %}>
                                {{ product.name }}</a></h2>
                            <p class="mt-30">{{ product.description }}</p>
                            <div class="button-box section-space--mt_60">
                                <a class="btn btn--md btn--border_1" href={% url 'product_detail' product.slug %}
                                >فقط {{ product.price }} تومان&nbsp;<i class="icon-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    {#                    <div class="images-text-bg text-end">#}
    {#                        <img src={% static "images/text-bg/bg-df-1-300x49.we %}bp" class="img-fluid" width="300" height="49" alt="Wood Coth"/>#}
    {#                    </div>#}
        </div>
    {% endfor %}
    <div class="product-wrapper section-space--ptb_120">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title text-center mb-20">
                        <h2 class="section-title--one section-title--center">بیشترین فروش</h2>
                    </div>
                </div>
            </div>
            <div class="product-slider-active">
                {% for product in fetured_products %}
                    {% if product.out_of_stock %}
                        <!-- Single Product Item Start -->
                        <div class="single-product-item text-center">
                            <div class="products-images"> <a href="product-details.html" class="product-thumbnail"> <img src={{product.image.url}} class="img-fluid" alt="Product Images" width="300" height="300" width="300" height="300"/> <span class="ribbon out-of-stock">اتمام موجودی</span> </a>
                                {% comment %} <div class="product-actions"> <a href="#" data-bs-toggle="modal" data-bs-target="#prodect-modal"><i class="p-icon icon-plus"></i><span class="tool-tip">مشاهده جزئیات</span></a> <a href="product-details.html"><i class="p-icon icon-bag2"></i> <span class="tool-tip">افزودن به سبد خرید</span></a> <a href="wishlist.html"><i class="p-icon icon-heart"></i> <span class="tool-tip">افزودن به علاقه مندی ها</span></a>
                                </div> {% endcomment %}
                            </div>
                            <div class="product-content">
                                <h6 class="prodect-title"><a href="product-details.html">{{product.name}}</a></h6>
                                <div class="prodect-price"> <span class="new-price">{{product.clean_price}}</span> * <span class="old-price">{{product.quantity}}</span></div>
                                </div>
                            </div>
                        </div>
                        <!-- Single Product Item End -->
                    {% endif %}
                    <!-- Single Product Item Start -->
                    <div class="single-product-item text-center">
                        <div class="products-images"> <a href="product-details.html" class="product-thumbnail"> <img src={{product.image.url}} class="img-fluid" alt="Product Images" width="300" height="300"/> </a>
                            <div class="product-actions"> <a href={% url 'products:product_detail' product.slug %}><i class="p-icon icon-plus"></i><span class="tool-tip">مشاهده جزئیات</span></a>   
                                <a href={% url 'products:add_to_wishlist' product.slug %}><i class="p-icon icon-heart"></i> <span class="tool-tip">افزودن به علاقه مندی ها</span></a>
                            </div>
                        </div>
                        <div class="product-content">
                            <h6 class="prodect-title"><a href="product-details.html">{{product.name}}</a></h6>
                            <div class="prodect-price"> <span class="new-price">{{product.clean_price}}</span> * <span class="old-price">{{product.quantity}}</span></div>
                        </div>
                    </div>
                    <!-- Single Product Item End -->
                    {% comment %} data-bs-toggle="modal" data-bs-target="#prodect-modal" {% endcomment %}
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="offer-colection-area container-fluid">
        <div class="section-space--ptb_120 bg-img" data-bg "images/bg/h1-countdown.jpg">
            <div class="row">
                <div class="container">
                    <div class="row ps-md-1 ps-3 pe-md-1 pe-3">
                        <div class="col-lg-7 col-md-7">
                            <div class="colection-info-wrap">
                                <div class="section-title mb-30">
                                    <h2 class="section-title--one ">مجموعه چوب <span class="text-red">50% تخفیف</span></h2>
                                </div>
                                <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است.</p>
                                <div class="timer text-center section-space--mt_60">
                                    <!-- countdown start -->
                                    <div class="countdown-deals counter-style--one" data-countdown="2022/12/01"></div>
                                    <!-- countdown end -->
                                </div>
                                <div class="button-box section-space--mt_60"> <a href="shop-4-column.html" class="btn--md btn--black btn">الآن خرید کنید <i class="icon-arrow-right"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}